// Remove all auto-generated hisaab entries (invoice/payment/order related)
// Keep only manual entries (loans)
import { initializeApp } from 'firebase/app';
import { getFirestore, collection, getDocs, doc, writeBatch } from 'firebase/firestore';

const firebaseConfig = {
  apiKey: "AIzaSyBJsDVAI_b7RvnSf-cpnSNLXQ-R0OH0qU4",
  authDomain: "hom-pos-52710474-ceeea.firebaseapp.com",
  projectId: "hom-pos-52710474-ceeea",
  storageBucket: "hom-pos-52710474-ceeea.firebasestorage.app",
  messagingSenderId: "288366939838",
  appId: "1:288366939838:web:044c8eec0a5610688798ef"
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

async function main() {
  const snap = await getDocs(collection(db, 'hisaab'));

  const toDelete = [];
  const toKeep = [];

  for (const d of snap.docs) {
    const entry = d.data();
    const desc = entry.description || '';
    // Auto-generated entries match these patterns
    const isAutoGenerated =
      /^Invoice INV-/.test(desc) ||
      /^Payment for Invoice INV-/.test(desc) ||
      /^Final Invoice INV-/.test(desc) ||
      /^Advance for Order ORD-/.test(desc);

    if (isAutoGenerated) {
      toDelete.push({ id: d.id, desc });
    } else {
      toKeep.push({ id: d.id, desc });
    }
  }

  console.log(`Entries to DELETE (${toDelete.length}):`);
  for (const e of toDelete) console.log(`  ${e.id} — ${e.desc}`);

  console.log(`\nEntries to KEEP (${toKeep.length}):`);
  for (const e of toKeep) console.log(`  ${e.id} — ${e.desc}`);

  if (toDelete.length === 0) {
    console.log('\nNothing to delete.');
    process.exit(0);
  }

  const batch = writeBatch(db);
  for (const e of toDelete) batch.delete(doc(db, 'hisaab', e.id));
  await batch.commit();
  console.log(`\n✅ Deleted ${toDelete.length} auto-generated hisaab entries.`);
  process.exit(0);
}

main().catch(e => { console.error(e); process.exit(1); });
